import Navigation from "./components/navigation"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-slate-900 text-white p-4 text-center">
          <Navigation/>
        </header>
        {children}
        <footer className="bg-slate-900 text-white p-4 text-center">
          <p>Madiha Aijaz</p>
        </footer>
      </body>
    </html>
  );
}
